env:
  es2021: true
  node: true
extends: standard
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent: ["error", 4]
  padded-blocks: 0
  semi: ["error", "always"]
  space-before-function-paren: 0
