name: Markdown Syntax Validation
on: [push, workflow_dispatch]

jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@master

      - name: Validate Markdown
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
            command: config
            globs: |
              .markdownlint.json
              **/*.md
              #**/node_modules
